runtime: nodejs18

instance_class: F1

env_variables:
  NODE_ENV: 'production'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

handlers:
  - url: /_next/static
    static_dir: .next/static

  - url: /.*
    script: auto
